# ConvNeXt backbone + FPN decoder + heatmap head
pretrained_model_name: facebook/dinov3-convnext-base-pretrain-lvd1689m

backbone:
  freeze: true
  return_stages: [0, 1, 2, 3, 4]
  device_map: auto
  local_files_only: true

fpn:
  lateral_dim: 256
  fuse: sum      # 'sum' or 'concat'

heatmap:
  # Target heatmap size [W, H]
  size: [256, 144]
  sigma: 2.0
