# ConvNeXt backbone + FPN decoder + heatmap head
pretrained_model_name: facebook/dinov3-convnext-base-pretrain-lvd1689m

backbone:
  use_pretrained: true  # offline fallback by default; set true when cached
  tv_model: convnext_tiny
  freeze: true

fpn:
  lateral_dim: 256
  use_p2: false
  fuse: sum

heatmap:
  # Target heatmap size [W, H]
  size: [256, 144]
  sigma: 2.0
