# ViT backbone + upsampling decoder + heatmap head
pretrained_model_name: facebook/dinov3-vitb16-pretrain-lvd1689m

decoder:
  # Channel plan including input (C) -> ... -> output map
  channels: [384, 256, 128, 64]
  # Upsample factors between stages
  upsample: [2, 2, 2]

heatmap:
  # Target heatmap size [W, H]
  size: [128, 72]
  sigma: 2.0

