# ViT backbone + upsampling decoder + heatmap head
pretrained_model_name: facebook/dinov3-vits16-pretrain-lvd1689m

backbone:
  freeze: true
  device_map: auto
  local_files_only: true
  patch_size: 16

decoder:
  # Channel plan including input (C) -> ... -> output map
  channels: [384, 256, 128, 64]
  # Upsample factors between stages
  upsample: [2, 2, 2]
  blocks_per_stage: 1
  norm: gn           # 'gn' or 'bn'
  activation: gelu   # 'gelu' or 'relu'
  use_depthwise: true
  use_se: false
  se_reduction: 8
  dropout: 0.0

heatmap:
  # Target heatmap size [W, H]
  size: [256, 144]
  sigma: 2.0
