# Optimization and training defaults
seed: 42

batch_size: 32
epochs: 20
amp: true  # deprecated; use `precision` if可能
precision: fp16  # one of: fp32, fp16, bf16
grad_clip: 1.0
backbone_freeze_epochs: 10

# Adaptive micro-batching settings
adaptive_micro_batch: true  # 必要になったら自動で分割
min_micro_batch_size: 4  # これ以下にはしない
mb_backoff_factor: 2  # 2で半減
oom_retries: 3  # 失敗しても数回は再試行
micro_batch_size: 0  # 0なら固定せず自動
grad_clip_norm: 1.0  # 任意

# DataLoader performance tuning
data_loader:
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 2
  drop_last: false

optimizer:
  name: adamw
  lr: 5.0e-4
  weight_decay: 0.05

scheduler:
  name: cosine
  warmup_epochs: 3
  warmup_start_factor: 0.1

# Output directories (resolved and created by utils/config.py)
output_dir: outputs
log_dir: outputs/logs
ckpt_dir: outputs/checkpoints
