# Optimization and training defaults
seed: 42

batch_size: 8
epochs: 1
amp: true  # deprecated; use `precision` if可能
precision: fp16  # one of: fp32, fp16, bf16
grad_clip: 1.0

# DataLoader performance tuning
data_loader:
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 2
  drop_last: false

optimizer:
  name: adamw
  lr: 5.0e-4
  weight_decay: 0.05

scheduler:
  name: cosine
  warmup_epochs: 5

# Output directories (resolved and created by utils/config.py)
output_dir: outputs
log_dir: outputs/logs
ckpt_dir: outputs/checkpoints
